# Generated by Django 5.1.2 on 2024-10-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todoname',
            new_name='todo_name',
        ),
    ]
